import { CoffeeCardType } from '../CoffeeCard'
import { coffeeImage } from './assets'

export const cards: CoffeeCardType[] = [
  {
    id: crypto.randomUUID(),
    tags: ['tradicional'],
    urlImg: coffeeImage.expressoTracional,
    title: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 9.9,
  },
  {
    id: crypto.randomUUID(),
    tags: ['tradicional'],
    urlImg: coffeeImage.expressoAmericano,
    title: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: 9.9,
  },
  {
    id: crypto.randomUUID(),
    tags: ['tradicional'],
    urlImg: coffeeImage.expressoCremoso,
    title: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    price: 9.9,
  },
  {
    id: crypto.randomUUID(),
    tags: ['tradicional', 'gelado'],
    urlImg: coffeeImage.expressoGelado,
    title: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    price: 9.9,
  },
  {
    id: crypto.randomUUID(),
    tags: ['tradicional', 'com leite'],
    urlImg: coffeeImage.cafeComLeite,
    title: 'Café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 9.9,
  },
  {
    id: crypto.randomUUID(),
    tags: ['tradicional', 'com leite'],
    urlImg: coffeeImage.latte,
    title: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: 9.9,
  },
  {
    id: crypto.randomUUID(),
    tags: ['tradicional', 'com leite'],
    urlImg: coffeeImage.capuccino,
    title: 'Capuccino',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 9.9,
  },
  {
    id: crypto.randomUUID(),
    tags: ['tradicional', 'com leite'],
    urlImg: coffeeImage.macchiato,
    title: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    price: 9.9,
  },
  {
    id: crypto.randomUUID(),
    tags: ['tradicional', 'com leite'],
    urlImg: coffeeImage.mocaccino,
    title: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 9.9,
  },
  {
    id: crypto.randomUUID(),
    tags: ['tradicional', 'com leite'],
    urlImg: coffeeImage.chocolateQuente,
    title: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 9.9,
  },
  {
    id: crypto.randomUUID(),
    tags: ['especial', 'alcoólico', 'gelado'],
    urlImg: coffeeImage.cubano,
    title: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 9.9,
  },
  {
    id: crypto.randomUUID(),
    tags: ['especial'],
    urlImg: coffeeImage.havaiano,
    title: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    price: 9.9,
  },
  {
    id: crypto.randomUUID(),
    tags: ['especial'],
    urlImg: coffeeImage.arabe,
    title: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    price: 9.9,
  },
  {
    id: crypto.randomUUID(),
    tags: ['especial', 'alcoólico'],
    urlImg: coffeeImage.irlandes,
    title: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 9.9,
  },
]
